FROM node:lts-alpine

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

RUN npm config set unsafe-perm true
RUN npm install @vue/cli@4.5.13 --location=global

COPY package.json .
COPY package-lock.json .

RUN npm install

#RUN chown -R node /app/node_modules

USER node

CMD ["npm", "run", "serve"]